apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: pci
  name: payments-policy
spec:
  podSelector:
    matchLabels:
      app: payments
  policyTypes:
  - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              role: infrastructure 