apiVersion: v1
kind: Namespace
metadata:
  name: management-ui 
  labels:
    role: management-ui 
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    requires: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    requires: queue
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    role: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: pci
  labels:
    requires: queue