apiVersion: v1
kind: Service
metadata:
  name: management-ui 
  namespace: management-ui 
spec:
  type: NodePort
  ports:
  - port: 9001 
    targetPort: 9001
    nodePort: 33002
  selector:
    role: management-ui 
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: management-ui 
  namespace: management-ui 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        role: management-ui 
        app: web-ui
    spec:
      containers:
      - name: management-ui 
        image: dockersamples/star-collect:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9001