apiVersion: v1
kind: Service
metadata:
  name: backend 
  namespace: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379 
  selector:
    app: backend 
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend 
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        role: backend
        app: backend 
    spec:
      containers:
      - name: backend 
        image: dockersamples/star-probe
        imagePullPolicy: Always
        command:
        - probe
        - --http-port=6379
        - --urls=http://facade.backend:80/status,http://payments.pci:6380/status,http://backend.backend:6379/status,http://client.frontend:9000/status,http://queue.infrastructure:5000/status
        ports:
        - containerPort: 6379 