apiVersion: v1
kind: Service
metadata:
  name: facade 
  namespace: backend
spec:
  ports:
  - port: 80 
    targetPort: 80 
  selector:
    app: facade
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: facade 
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facade
  template:
    metadata:
      labels:
        role: backend 
        app: facade
    spec:
      containers:
      - name: facade 
        image: dockersamples/star-probe
        imagePullPolicy: Always
        command:
        - probe
        - --http-port=80
        - --urls=http://facade.backend:80/status,http://payments.pci:6380/status,http://backend.backend:6379/status,http://client.frontend:9000/status,http://queue.infrastructure:5000/status
        ports:
        - containerPort: 80 